inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - ext/**/*
    - lib/temporalio/api/**/*
    - target/**/*
    - tmp/**/*
    - vendor/**/*

# Keep cop rule settings in alphabetical order

# We want development dependencies in the gemspec
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - temporalio.gemspec
    - Rakefile
    - spec/**/*_spec.rb

Style/GlobalVars:
  Exclude:
    - spec/**/*