name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        # TODO(cretz): Enable Windows (it's slow)
        # os: [ubuntu-latest, macos-12, windows-latest]
        os: [ubuntu-latest, macos-12]

        # TODO(cretz): Enable all versions
        # rubyVersion: ["3.1", "3.2", "3.3"]
        rubyVersion: ["3.3"]
        
        include:
          - os: ubuntu-latest
            rubyVersion: "3.3"
            checkTarget: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.rubyVersion }}
          bundler-cache: true
          cargo-cache: true

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          # TODO(cretz): Can upgrade proto when https://github.com/arduino/setup-protoc/issues/99 fixed
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Rust
        if: ${{ matrix.checkTarget }}
        run: cargo clippy && cargo fmt --check

      - name: Lint, compile, test Ruby
        run: bundle exec rake
